### ISSUE TITLE
unit price and unit limit

### ISSUE THREAD

**Issue by AL-THE-BOT-FATHER** [leq6c/soldexpy#2]
In your library do the the unit price and unit limit values affect the "priority" of the transaction?

Have you experimented with different values?

Thank you again for this code base. 

Is there any way to reach out to you directly?

![pri fee](https://github.com/leq6c/soldexpy/assets/98119917/5f2a80a3-7830-4f40-8294-aa83894b35c9)

**Comment by leq6c** [comment]
It does. But I don't think it has much effect on the ordering in the block. 

You may reach me on discord @tooles

**Comment by AL-THE-BOT-FATHER** [comment]
> It does. But I don't think it has much effect on the ordering in the block.
> 
> You may reach me on discord @Tooles

Do you have a Telegram?
